{
 "title": "Job Queue",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Queue available size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(max_over_time(job_queue_available_length[$__interval])) by (job_queue)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queue size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(max_over_time(job_queue_length[$__interval])) by (job_queue)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Jobs queued",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(jobs_queued_total[$__rate_interval])) by (job_name)"
    }
   ]
  },
  {
   "title": "Jobs processed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(jobs_processed_total{status=\"processed\"}[$__rate_interval])) by (job_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Jobs failed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(jobs_processed_total{status=\"failed\"}[$__rate_interval])) by (job_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Job start duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (increase(job_start_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (increase(job_start_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (increase(job_start_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Job duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5,sum(increase(job_duration_seconds_bucket{status=\"processed\"}[$__rate_interval])) by (le))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.9,sum(increase(job_duration_seconds_bucket{status=\"processed\"}[$__rate_interval])) by (le))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.99,sum(increase(job_duration_seconds_bucket{status=\"processed\"}[$__rate_interval])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Job failed duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5,sum(sum_over_time(job_duration_seconds_bucket{status=\"failed\"}[$__interval])) by (le))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.9,sum(sum_over_time(job_duration_seconds_bucket{status=\"failed\"}[$__interval])) by (le))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.99,sum(sum_over_time(job_duration_seconds_bucket{status=\"failed\"}[$__interval])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}