{
 "title": "Performance",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Average DB Queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (type, job_name, command, http_request_method, http_route) (increase(db_queries_sum[$__rate_interval])) / sum by (type, job_name, command, http_request_method, http_route) (increase(db_queries_count[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (type, job_name, command, http_request_method, http_route) (increase(process_memory_usage_MiB_sum[$__rate_interval])) / sum by (type, job_name, command, http_request_method, http_route) (increase(process_memory_usage_MiB_count[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Time Taken (HTTP)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (http_request_method, http_route) (increase(http_server_request_duration_seconds_sum[$__rate_interval])) / sum by (http_request_method, http_route) (increase(http_server_request_duration_seconds_count[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Time Taken (Jobs)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (job_name) (increase(job_duration_seconds_sum[$__rate_interval])) / sum by (job_name) (increase(job_duration_seconds_count[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}