{
 "title": "RED",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Requests",
   "type": "timeseries",
   "description": "the number of requests our service is serving per second",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error %",
   "type": "timeseries",
   "description": "the number of failed requests per second",
   "gridPos": { "h": 7, "w": 8, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum (rate(http_server_request_duration_seconds_count{http_response_status_code!~\"2..\"}[$__rate_interval])) / sum (rate(http_server_request_duration_seconds_count[$__rate_interval])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "timeseries",
   "description": "the amount of time it takes to process a request",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_request_duration_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests by route",
   "type": "timeseries",
   "description": "the number of requests our service is serving per second per route",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (http_route) (rate(http_server_request_duration_seconds_count[$__rate_interval]))",
     "legendFormat": "{{http_route}}"
    }
   ]
  },
  {
   "title": "Errors per route",
   "type": "timeseries",
   "description": "the number of failed requests per second",
   "gridPos": { "h": 7, "w": 8, "x": 7, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (http_route) (rate(http_server_request_duration_seconds_count{http_response_status_code!~\"2..\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Slowest HTTP routes (P95)", "gridPos": { "h": 7, "w": 9, "x": 15, "y": 7 } }
 ]
}