receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
      grpc:
        endpoint: 0.0.0.0:4317

exporters:
  logging:
    # loglevel: debug
    verbosity: detailed
  influxdb:
    endpoint: http://influxdb:8086
    org: stickee
    bucket: test
    token: my-super-secret-auth-token

  loki:
    endpoint: http://loki:3100/loki/api/v1/push

  otlphttp/tempo:
    endpoint: http://tempo:4318
    tls:
      insecure: true

  otlphttp/prometheus:
    endpoint: http://prometheus:9090/api/v1/otlp
    tls:
      insecure: true

processors:
  batch:

  # https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/transformprocessor
  transform:
    log_statements:
      - context: resource
        statements:
          - keep_keys(attributes, [])
      # - context: scope
      #   statements:
      #     - keep_keys(attributes, ["logs"])
      #- context: log
      #  statements:
      #    - set(attributes["value"], attributes["body"])
      #    - keep_keys(attributes, ["observed_timestamp", "event.domain", "event.name", "value"])

service:
  pipelines:
    logs:
      receivers:
        - otlp
      processors:
        - batch
      exporters:
        - logging
        - loki

    logs/kpis:
      receivers:
        - otlp
      processors:
        - transform
        - batch
      exporters:
        - logging
        - influxdb

    metrics:
      receivers:
      - otlp
      processors:
        - batch
      exporters:
      - logging
      - otlphttp/prometheus

    traces:
      receivers:
        - otlp
      processors:
        - batch
      exporters:
        - logging
        - otlphttp/tempo
