receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318

exporters:
  debug:
    verbosity: detailed

  loki:
    endpoint: http://loki:3100/loki/api/v1/push

  otlphttp/tempo:
    endpoint: http://tempo:4318
    tls:
      insecure: true

  otlphttp/prometheus:
    endpoint: http://prometheus:9090/api/v1/otlp
    tls:
      insecure: true

processors:
  # https://github.com/open-telemetry/opentelemetry-collector/blob/main/processor/batchprocessor
  batch:
    timeout: 1s

  # https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/deltatocumulativeprocessor
  deltatocumulative:

  # Stickee's custom processor
  # https://github.com/stickeeuk/opentelemetry-collector-contrib
  aggregation:
    interval: 15s

service:
  telemetry:
    logs:
      level: DEBUG
  pipelines:
    logs:
      receivers:
        - otlp
      processors:
        - batch
      exporters:
        - debug
        - loki

    metrics:
      receivers:
        - otlp
      processors:
        - aggregation
        - deltatocumulative
        - batch
      exporters:
        - debug
        - otlphttp/prometheus

    traces:
      receivers:
        - otlp
      processors:
        - batch
      exporters:
        - debug
        - otlphttp/tempo
