receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
      grpc:
        endpoint: 0.0.0.0:4317

exporters:
  logging:
    verbosity: detailed

  loki:
    endpoint: http://loki:3100/loki/api/v1/push

  otlphttp/tempo:
    endpoint: http://tempo:4318
    tls:
      insecure: true

  otlphttp/prometheus:
    endpoint: http://prometheus:9090/api/v1/otlp
    tls:
      insecure: true

processors:
  batch:
  deltatocumulative:

service:
  pipelines:
    logs:
      receivers:
        - otlp
      processors:
        - batch
      exporters:
        - logging
        - loki

    metrics:
      receivers:
      - otlp
      processors:
        - deltatocumulative
        - batch
      exporters:
      - logging
      - otlphttp/prometheus

    traces:
      receivers:
        - otlp
      processors:
        - batch
      exporters:
        - logging
        - otlphttp/tempo
