receivers:
  otlp:
    protocols:
      http:
        endpoint: localhost:4318

processors:
  aggregation: null
  batch: null
  deltatocumulative: null
  filter/drop_post_to_collector:
    traces:
      span:
      - attributes["url.full"] == "http://localhost:4318/v1/logs"
      - attributes["url.full"] == "http://localhost:4318/v1/metrics"
      - attributes["url.full"] == "http://localhost:4318/v1/traces"
  filter/log_level:
    error_mode: ignore
    logs:
      log_record:
      - severity_number < SEVERITY_NUMBER_INFO
  resourcedetection:
    detectors:
    - env
    - system
    override: false
  transform/add_resource_attributes_as_metric_attributes:
    error_mode: ignore
    metric_statements:
    - context: datapoint
      statements:
      - set(attributes["deployment.environment.id"], resource.attributes["deployment.environment.id"])
      - set(attributes["deployment.environment.name"], resource.attributes["deployment.environment.name"])
      - set(attributes["service.version"], resource.attributes["service.version"])
  transform/drop_unneeded_resource_attributes:
    error_mode: ignore
    log_statements:
    - context: resource
      statements:
      - delete_key(attributes, "k8s.pod.start_time")
      - delete_key(attributes, "os.description")
      - delete_key(attributes, "os.type")
      - delete_key(attributes, "process.command_args")
      - delete_key(attributes, "process.executable.path")
      - delete_key(attributes, "process.pid")
      - delete_key(attributes, "process.runtime.description")
      - delete_key(attributes, "process.runtime.name")
      - delete_key(attributes, "process.runtime.version")
    metric_statements:
    - context: resource
      statements:
      - delete_key(attributes, "k8s.pod.start_time")
      - delete_key(attributes, "os.description")
      - delete_key(attributes, "os.type")
      - delete_key(attributes, "process.command_args")
      - delete_key(attributes, "process.executable.path")
      - delete_key(attributes, "process.pid")
      - delete_key(attributes, "process.runtime.description")
      - delete_key(attributes, "process.runtime.name")
      - delete_key(attributes, "process.runtime.version")
    trace_statements:
    - context: resource
      statements:
      - delete_key(attributes, "k8s.pod.start_time")
      - delete_key(attributes, "os.description")
      - delete_key(attributes, "os.type")
      - delete_key(attributes, "process.command_args")
      - delete_key(attributes, "process.executable.path")
      - delete_key(attributes, "process.pid")
      - delete_key(attributes, "process.runtime.description")
      - delete_key(attributes, "process.runtime.name")
      - delete_key(attributes, "process.runtime.version")

exporters:
  otlphttp/grafana_cloud:
    auth:
      authenticator: basicauth/grafana_cloud
    endpoint: https://otlp-gateway-prod-eu-west-2.grafana.net/otlp

extensions:
  basicauth/grafana_cloud:
    client_auth:
      password: 'This is a password'
      username: '709587'

service:
  extensions:
  - basicauth/grafana_cloud
  pipelines:
    logs:
      exporters:
      - otlphttp/grafana_cloud
      processors:
      - resourcedetection
      - filter/log_level
      - transform/drop_unneeded_resource_attributes
      - batch
      receivers:
      - otlp
    metrics:
      exporters:
      - otlphttp/grafana_cloud
      processors:
      - resourcedetection
      - transform/drop_unneeded_resource_attributes
      - transform/add_resource_attributes_as_metric_attributes
      - aggregation
      - deltatocumulative
      - batch
      receivers:
      - otlp
    metrics/grafanacloud:
      exporters:
      - otlphttp/grafana_cloud
      processors:
      - batch
      receivers:
      - grafanacloud
    traces:
      exporters:
      - otlphttp/grafana_cloud
      - grafanacloud
      processors:
      - resourcedetection
      - filter/drop_post_to_collector
      - transform/drop_unneeded_resource_attributes
      - batch
      receivers:
      - otlp

connectors:
  grafanacloud:
    host_identifiers:
    - host.name
