services:
  influxdb:
    image: influxdb:2.7-alpine
    restart: always
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=Password123
      - DOCKER_INFLUXDB_INIT_ORG=stickee
      - DOCKER_INFLUXDB_INIT_BUCKET=test
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-super-secret-auth-token
    ports:
      - '8086:8086'
    volumes:
      - influxdb_data:/var/lib/influxdb
    networks:
      - influxdb_network

  chronograf:
    image: chronograf:1.9-alpine
    command: ["chronograf", "--influxdb-url=http://influxdb:8086"]
    restart: always
    ports:
      - '8888:8888'
    depends_on:
      - influxdb
    networks:
      - influxdb_network

networks:
  influxdb_network:
    driver: bridge
volumes:
  influxdb_data:
    driver: local
